services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sward
      POSTGRES_PASSWORD: sward
      POSTGRES_DB: usuarios_db
    ports:
      - "5433:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
  app:
    build: .
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://sward:sward@db:5432/usuarios_db
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
    depends_on:
      - db
      - redis
