from abc import ABC, abstractmethod
from uuid import UUID


class CachePort(ABC):
    @abstractmethod
    async def get_permisos(self, usuario_id: UUID) -> list[str] | None: ...
    @abstractmethod
    async def set_permisos(
        self, usuario_id: UUID, permisos: list[str], ttl: int
    ) -> None: ...
    @abstractmethod
    async def invalidar_permisos(self, usuario_id: UUID) -> None: ...
    @abstractmethod
    async def incrementar_intentos_login(self, correo: str, ttl: int) -> int: ...
    @abstractmethod
    async def get_intentos_login(self, correo: str) -> int: ...
    @abstractmethod
    async def limpiar_intentos_login(self, correo: str) -> None: ...
    @abstractmethod
    async def blacklist_token(self, jti: str, ttl_segundos: int) -> None: ...
    @abstractmethod
    async def is_token_blacklisted(self, jti: str) -> bool: ...
    @abstractmethod
    async def save_refresh_token(
        self, usuario_id: UUID, device_id: str, token_hash: str, ttl: int
    ) -> None: ...
    @abstractmethod
    async def get_refresh_token(
        self, usuario_id: UUID, device_id: str
    ) -> str | None: ...
    @abstractmethod
    async def invalidar_todos_refresh_tokens(self, usuario_id: UUID) -> None: ...
